CREATE DATABASE Dados;

USE Dados;

CREATE TABLE CNHs
(
	idCNH		INT PRIMARY KEY IDENTITY
	,CNH		VARCHAR(350) NOT NULL
);

CREATE TABLE Pessoas
(
	idPessoa	INT PRIMARY KEY IDENTITY
	,idCNH		INT FOREIGN KEY REFERENCES CNHs (idCNH)
	,Nome		VARCHAR(300) NOT NULL
);

CREATE TABLE Emails
(
	idEmail		INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoas (idPessoa)
	,Email		VARCHAR(150) NOT NULL
);


CREATE TABLE Telefones
(
	idTelefone	INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoas (idPessoa)
	,Telefone	VARCHAR(200) NOT NULL
);